V1.10 (#20)
* improve interactions + badmeme

- add badmeme interaction
- fix error when defer option wasn't set but an interaction was deferred
- fix TypeError in badmeme
- expose `@khaf/badmeme` cache.
- delete reply when an interaction doesn't reply with a string or embed object. fixes "infinite" loading

* embed talkobamatome video in discord

* fix `openlibrary` TypeError, limit results to 1

* initial SQLite support

- much better worker_threads implementation that doesn't rely on passing functions around or comparing functions, etc.
- errors are *still* being swallowed by worker_threads, so we catch the error in the worker and log it there.
- convert `branco` command to SQLite.

* migrate `garrison` to sqlite

* migrate `stonewall` to sqlite

* add script to dump postgres tables

- remove `GarrisonDump` command

* respect syndication frequency rss feed options

- Respects a feed's [syndication frequency and period](https://web.resource.org/rss/1.0/modules/syndication/) if the options are both present and valid. Otherwise the feed will not be refreshed.
- Add in more type checks and safety features to prevent a badly formed feed from causing errors.

* fix(!crypto): currencies can have duplicate symbols

- allows searching by the ID now - IDs aren't joined by a space but by a dash.
- if multiple cryptos are found with a query, the bot will now display all of the unique IDs so the user can get the currency they want.

* update discord.js typings

- glad to see strict(-ish) types finally

* improve typings

* Update package-lock.json

* PocketInit: use buttons instead of reactions

* add buttons to `banprompt` and `softbanprompt`

- add reusable `Components`

* create global slash commands

* add owner only `eval` command

* vm.compileFunction can throw

* remove guild region, fix undefined max args message

* transform command return into MessageOptions

- discord.js is planning to remove loose parameter types for a bunch of methods, including channel.send and message.reply.
- this is a good change and doesn't actually affect anything. rather than the transformations being done behind the scenes they're done here instead.

* use MessageOptions for all replies and sends

* clear crypto cache 🤦

* server: add partnered/verified status, remove large

- uses guild locale to format numbers
- replaces `large` with `verified`.
- add `partnered` guild status

* patch eval

* use `Snowflake` type

* improve `CLITable` module, `user` command

- table function is now much easier to use and understand
- memoize emojis for user command using the existing utility.

* add overly complicated `emojiinfo` command

- ripped unicode emoji names/etc. from Discord, will need to be updated every now and again to keep up to date info.

* update button collectors

- removes buttons on time end
- updates to new discord.js functionality

* transform `edit()` method params

* update `theonion` command

- IDs are no longer stored in a JSON file (the file was never actually updated anyways)
- parses RSS feed and gets the article from there instead now.

* add mod logs to `banprompt` and `massban`,

- reliably sets the unban/ban cache that tracks the staff who banned/unbanned/etc. a user
- no longer sets if the user isn't banned (due to some error), preventing memory leaks by having a potentially ever-growing cache

* update `validateSnowflake`, allow mentions in `massban`

- `validateSnowflake` will no longer throw if the argument passed to it isn't a string
- `validateSnowflake` now asserts the type
- `massban` now allows mentioning users along with passing id strings!

* update to latest d.js commit

* add more flags to `user` command

* remove `Fetcher` structure, add `onion` interface

* remove MessageEmbed#attachFiles

- also made `thisdoesnotexist` utility function more maintainable

* update discord.js

- `post` rules now sends multiple embeds instead of 1 at a time(!!!)
- `post` rules now removes the need for a webhook

* use buttons for pagination

* use buttons to paginate (badmeme, yt, tnp)

* fix `crypto`, `thisxdoesnotexist`, `wyl` commands

* remove `wyl` command

* organization

- remove `Forgotify` command
- change `trumpkey` arguments to fit the command
- move `avatar` from Fun -> Server category

* I made a calculator in Discord

* use vm.* for `eval` and `calc`

- Also fixes issue where the entire `lastAction` would be replaced if the number was just zero(es).

* fix(calc): some characters being ignored

- roll my own limits so that `lastAction` is correctly appended to `actions`.

* normalize calculator "screen" size

* use new line for long answers

* use object w/ null prototype for vm context

* allow `chan` to search by name, improve Snowflake validator util

- fixes error with `user` command.
- `validSnowflake` now checks if the given id is a number 17-19 characters long from start to end.
- `channel` command can now be used by passing in a channel's name

* fix `crypto` loading times

- replaces duplicates rather than clearing the entire cache now. Item will always be cached because of this change after the first run.

* remove `longestpoemintheworld` and  `any`s

* calc: add parenthesis + decimal

* fix input bugs

- remove custom use amount
- bump uses up to 15
- fix bug where the input wouldn't update when pressing =

* add 'react' roles!!!

- add react roles using buttons!
- add `reactRoleChannel` column to `kbGuild` table.
- rename `Warnings.d.ts` to `KhafraBot.d.ts`
- accept a string as a parameter to `validSnowflake`

* react role: remove role if member has it already

* react role: update message depending on action

* disable `failIfNotExists` by default

* add v1.10 changelog

* memoize `KhafraClient#init`, update d.js

* calc: multiply by parenthesis pair

* much better `addemoji` command

- removes check file type check (an image URL doesn't necessarily need to have an extension).
- allow ordering name/link in any order for easier usage.

* use args.length here lol

* validate url protocol

* add URL validator utility

* improve `awards` and `twitdl` url validation

* fix+strengthen `twitdl` url validation further

* rps now uses buttons

* improve `hangman`

- use button for hint
- remove now useless casts
- slightly improve code (use EventEmitter.once for hint collecting, etc.)

* improve `tictactoe`

- uses button + rows as the board
- remove formatted message and checks that no longer apply
- removes ability to play against another person

* use real private fields

* add `debug:button` command

* insights: fix unordered dates

* general `insights` improvements

- update query to remove results > 14 days old from `SELECT`.
- remove filtering from javascript side
- use one `Array.reduce` instead of 3 `Array.map`s to format the table results.

* add 1984 interaction

* drop old tables, update `cah`

- `cah` no longer uses a db, just gets a random cartoon from the 10 or so latest ones on the rss feed.
- finally drop old tables that weren't used

* fix parenthesis mult by decimal

* Delete CyanideAndHappiness.ts

* transition from `node-fetch` to `undici-fetch`

* fully transition to `undici-fetch`

* use `node-fetch` when passing body

- https://github.com/Ethan-Arrowood/undici-fetch/pull/59

* update to latest d.js

* add `ACLU` command

* add `superscript` text command

* improve `blocktext`

- allow uppercase characters
- allow emojis and other characters that aren't block emojis

* improve `piglatin`

- faster, doesn't use regex
- better commented, less hacks

* use undici-fetch in more places

* use permanent `aclu` rss feed link

* rss: use non-redirected links and notify when redirected

* add "back" `xkcd` command

* Create ci.yml

* update collectors

* Update Stonewall.ts

* disable components when done

* add time remaining to hangman games

* move more towards undici-fetch

* Create Blackjack.ts

* remove old deps from packages

* update ci

* update packages

* fix-invalid-command-names-working

* new strawpoll command

* fix hangman win condition

- winning now works if you guess all characters correctly, not just by guessing the entire word.

* actually fix win cond. + remove components on game end

* fix error message on first warning

* update d.js

* stop creating this table

* update to ts 4.4.0 beta

* eslint

* properly type Pocket#add and fix TypeError

* fix deprecated events, add lint to ci

* add countries list to hangman

* add URLFactory opts, create reddit category + deleted posts command

* Update Deleted.ts

* Update Deleted.ts

* update discord.js

* update discord.js, patch d.js typings

* check message.deletable before deleting messages

* add `hacks:edit` command, move ghostping

* update d.js

* enable many more linting rules

* enable `@typescript-eslint/prefer-regexp-exec`

* add `no-unsafe-optional-chaining`

* welcome messages: stringify member

* improve `badmeme`

- optimize function by using a single loop
- improve typings (error reason, isgfycat)
- remove unreachable statements

* badmeme: fix stop button not working

* add comprehensive guild logging

- log emoji changes
- log role changes

* improve old events

- sets redis cache in events
- improves typings (narrows down, ensures changes don't break anything)

* enforce event types

* add channels to complete logs

* redis is absolute garbage

* modlog: fix ban/unban reason not working

* beginning non-functioning giveaways

- non functional giveaways (giveaways can be created but nothing else)
- better permission serialize util
- remove dm intent
- fix overloads in mention util

* finish giveaway implementation

* tsconfig: enable `strictFunctionTypes`

* double hangman game time

* set readonly properties for Command

* move tmdb & RSS util to undici-fetch

* update giveaway create, tmdb

- fix tmdb `Headers`
- giveaway creation now asks for the channel to create a giveaway in rather than using the first argument
- giveaway creation removes settings fields because they made it harder to understand
- remove description from every updated message after the first

* enable more eslint rules

* fix timestamp -> time conversion losing accuracy

* giveaway deleting + editing

- ids are now uuids
- improve `Command` typings
- remove `drops` for now.

* Update Hangman.ts

* improve warning commands

- if a member is kicked, the reason is now added
- fixed issue where warning points were miscalculated
- remove `k_id` (number) in turn for a better, more random/safe `uuid`.
- use more type safe `UUID4` type for Giveaway/Warning interfaces
- improve types in get/delete warnings to make them safe for updates
- better k_ts timestamp default.

* improve `help` command

* remove last instances of `node-fetch`

- new `cartoonize` command that just uses `https.request` (`undici-fetch` will eventually be used)
- update monorepo package.json/package-lock.json

* add individual command help

* lint

* fix `unwarn` command

* fix `warns`

* remove faulty migration

* functioning kbWarns migration

* remove low quality commands

* use <timer>.unref()

* fix spamming hangman command

* even more `hangman` safeguards

* https.request: add agent + AbortController

* remove unused logger

* notify user when hitting ratelimit

* safety-proof `message` event

- add utility function to catch errors thrown from promises and return the results in an array-like callback style.
- remove `dm` channel support that didn't work.

* hangman: fix some country names

* add more user flags

* add author to boost messages

* use `dontThrow` util for .catch(noop)

* use discord time formatters

* use more discord time formatters

* update discord.js

* help: disable components

* `channelinfo`: check for perms

- if a user knows (or guesses) a private channel that the bot has access to, but the user doesn't, it would display info about the channel. Now, perms to view the channel are checked before doing so.

* add `activity` command

* insights: revert 5feca3a

* `member`: fix TypeError

* w

* add more info to `guildMember(Add/Remove)` events

* Update Cartoonize.ts

* guildMemberAdd/Remove: don't use durations

* Update Activity.ts

* fix `help` TypeError

* update d.js

* use `dontThrow` everywhere

- inside of event emitters, errors cannot be caught by the current error handling. the `dontThrow` utility will now catch these errors without huge changes to syntax, blocks, etc.

* sql(`kbGuild`): set `id` as `uuid` type

* remove `formatDate` from last few commands

* add `padEmbedFields` utility

* fix `awards` url validation

* `channelUpdate`: fix TypeError

* fix: event listeners will no longer throw rejections

* few small updates

- `activity` command now uses the latest API version (v8 -> v9)
- `is[Channel]` now accepts any argument
- fix lint error with `dontThrow` fn

* updated + fixed `wikipedia` command

* `wikipedia`: disable select menu after idling

* Update Awards.ts

* `crypto` backend updates

- handle errors
- use `dontThrow` utility

* `bible`: add pg casts

* improve `nasa` command

- no longer uses `postgres` database

* Update Sticker.ts

* `sqlite3`: enable `WAL`

* lint

* enable `strictNullChecks` :tada:

* small `hangman` improvements

- games will now go on until there are either 6 wrong guesses OR they are idle for 30 seconds
- at the game's end, the component collector will now be stopped
- at the game's end, the hint button will be disabled and the bot will notify you that the game has ended

* fix empty `ban` reason

* Create CloneChannel.ts

* Update User.ts

* Create FThreads.ts

* Update FThreads.ts

* fix: `ratelimit` modlog sent wrong channel

* use new `FileWatcher` for json imports

* update d.js

* update d.js

* remove last json imports

* Update index.ts

* `piglatin`: fix punctuation

* remove complete log channel

- use audit logs

* update `rules` command

* Discord is a horrible platform lol

* better join/leave messages

* Fix: lacking `SELECT` statements leading to less than partial kGuild

* Update Message.ts

* `channelinfo`: add region

* assert

* Update Redis.ts

* new interaction loader

* add `reroll` to giveaways

* badmeme: type indicator when subreddit isn't cached

* lint